---
- name: Nginx | Make sure nginx is installed (package)
  apt:
    pkg: nginx
    state: present

- name: Nginx | Copying site
  template:
    src: nginx.config.tpl
    dest: "/etc/nginx/sites-available/registration.devmeetings.com"

- name: Nginx | Enabling XPlatform
  file: 
    src: "/etc/nginx/sites-available/registration.devmeetings.com"
    dest: "/etc/nginx/sites-enabled/registration.devmeetings.com" 
    state: link

- service: name=nginx state=restarted 
- service: name=nginx enabled=yes



