---
- name: Payments | Creating user
  user:
    name: payments
    comment: 'Use for registration and payments app'

- name: Payments | Directory /srv/
  file:
    path: /srv
    state: directory

- name: Payments | Directory /srv/_packages
  file:
    path: /srv/_packages
    state: directory

- name: Payments | Create directory for app
  file:
    path: /srv/{{ server_name }}
    state: directory
    mode: 0755
    owner: payments

- name: Payments | Verify newest version
  file:
    state: absent
    path: /srv/_packages/payments_{{payments_version}}.tar.gz
  when: payments_version == 'lastSuccessfulBuild'

- name: Payments | Fetching app
  command: "wget https://applejack.todr.me/job/{{payments_job}}/{{payments_version}}/artifact/payments.tar.gz --user builder --password 123Builder --auth-no-challenge -O /srv/_packages/payments_{{payments_version}}.tar.gz"
  args:
    creates: /srv/_packages/payments_{{payments_version}}.tar.gz

- name: Payments | Unpacking
  unarchive:
    copy: no
    dest: "/srv/{{ server_name }}"
    src: "/srv/_packages/payments_{{payments_version}}.tar.gz"

- name: Installing Modules
  npm:
    path: "/srv/{{ server_name }}/"

- name: Run On Startup
  command: pm2 startup -u payments --hp /srv/{{ server_name }}
  args:
    chdir: "/srv/{{ server_name }}"

- name: delete existing pm2 processes if running
  command: "pm2 delete {{ server_id }}"
  ignore_errors: True
  become: yes
  become_user: payments

- name: start pm2 process
  command: 'pm2 start --name "{{ server_id }}" app.js'
  args:
    chdir: "/srv/{{ server_name }}"
  become: yes
  become_user: payments
  environment:
    NODE_ENV: "{{payments_env}}"
    PORT: "{{payments_port}}"


